(() => {
  // <stdin>
  console.log("This site was generated by Hugo.");
  document.addEventListener("DOMContentLoaded", function() {
    relocateCalloutFootnotes();
    fixFootnoteIds();
    const backRefs = document.querySelectorAll(".footnote-backref");
    if (backRefs.length > 0) {
      backRefs.forEach((backref, index) => {
        const href = backref.getAttribute("href");
        if (!href) return;
        backref.style.fontWeight = "bold";
        backref.style.fontSize = "1.2em";
        backref.addEventListener("click", function(e) {
          e.preventDefault();
          const targetId = href.substring(1);
          const targetElement = document.getElementById(targetId);
          if (targetElement) {
            targetElement.scrollIntoView({ behavior: "smooth" });
            targetElement.classList.add("footnote-highlight");
            setTimeout(() => {
              targetElement.classList.remove("footnote-highlight");
            }, 2e3);
          }
        });
      });
    }
    const footnoteRefs = document.querySelectorAll(".footnote-ref");
    if (footnoteRefs.length > 0) {
      footnoteRefs.forEach((ref, index) => {
        const href = ref.getAttribute("href");
        ref.addEventListener("click", function(e) {
          e.preventDefault();
          const targetId = this.getAttribute("href").substring(1);
          const targetElement = document.getElementById(targetId);
          if (targetElement) {
            targetElement.scrollIntoView({ behavior: "smooth" });
          }
        });
      });
    }
  });
  function fixFootnoteIds() {
    const footnoteRefs = document.querySelectorAll('sup[id^="fnref"]');
    footnoteRefs.forEach((ref) => {
      const id = ref.id;
      const link = ref.querySelector("a");
      if (link) {
        const href = link.getAttribute("href");
        if (href) {
          const targetId = href.substring(1);
          const target = document.getElementById(targetId);
          if (target) {
            const backref = target.querySelector(".footnote-backref");
            if (backref) {
              backref.setAttribute("href", "#" + id);
              console.log(
                `\u4FEE\u590D\u811A\u6CE8\u8FD4\u56DE\u94FE\u63A5: ${backref.getAttribute("href")} \u6307\u5411 ${id}`
              );
            }
          }
        }
      }
    });
  }
  function relocateCalloutFootnotes() {
    const calloutFootnoteBlocks = Array.from(document.querySelectorAll(".callout .footnotes"));
    if (calloutFootnoteBlocks.length === 0) return;
    let globalFootnotes = Array.from(document.querySelectorAll(".footnotes")).find((el) => !el.closest(".callout"));
    const contentRoot = document.querySelector("article .p-8.prose") || document.querySelector(".p-8.prose");
    if (!globalFootnotes) {
      globalFootnotes = document.createElement("div");
      globalFootnotes.className = "footnotes";
      const hr = document.createElement("hr");
      const ol = document.createElement("ol");
      globalFootnotes.appendChild(hr);
      globalFootnotes.appendChild(ol);
      if (contentRoot) {
        contentRoot.appendChild(globalFootnotes);
      } else {
        document.body.appendChild(globalFootnotes);
      }
    }
    const globalList = globalFootnotes.querySelector("ol") || function() {
      const ol = document.createElement("ol");
      globalFootnotes.appendChild(ol);
      return ol;
    }();
    calloutFootnoteBlocks.forEach((block) => {
      const list = block.querySelector("ol");
      if (!list) return;
      Array.from(list.children).forEach((li) => {
        globalList.appendChild(li);
      });
      block.remove();
    });
  }
})();
